const products = [
  // 🎨 Paintings
  {
    id: "painting-001",
    name: "Golden Dawn",
    vendor: "Joan of Art",
    description: "Original oil painting, radiant with light and movement.",
    price: 750,
    productCode: "painting-001",
    gallery: [{ src: "/products/pdp1.jpeg", alt: "Golden Dawn painting" }],
    colorOptions: ["Original"],
    sizeOptions: ["Standard"],
  },
  {
    id: "painting-002",
    name: "Ethereal Bloom",
    vendor: "Joan of Art",
    description: "Soft floral painting with ethereal blending of colors.",
    price: 680,
    productCode: "painting-002",
    gallery: [{ src: "/products/pdp2.jpeg", alt: "Ethereal Bloom painting" }],
    colorOptions: ["Original"],
    sizeOptions: ["Standard"],
  },
  {
    id: "painting-003",
    name: "Urban Serenity",
    vendor: "Joan of Art",
    description: "Muted earth tones inspired by city life and calm reflection.",
    price: 720,
    productCode: "painting-003",
    gallery: [{ src: "/products/pdp3.jpeg", alt: "Urban Serenity painting" }],
    colorOptions: ["Original"],
    sizeOptions: ["Standard"],
  },
  {
    id: "painting-004",
    name: "Celestial Flow",
    vendor: "Joan of Art",
    description: "Abstract cosmic skies with flowing brushwork.",
    price: 800,
    productCode: "painting-004",
    gallery: [{ src: "/products/pdp4.jpeg", alt: "Celestial Flow painting" }],
    colorOptions: ["Original"],
    sizeOptions: ["Standard"],
  },

  // 👗 Clothing
  {
    id: "fashion-001",
    name: "JoanCheri Silk Wrap",
    vendor: "Joan of Art",
    description: "Luxury silk wrap with an abstract art-inspired print.",
    price: 220,
    productCode: "fashion-001",
    gallery: [{ src: "/products/shirt1.jpg", alt: "Silk Wrap fashion" }],
    colorOptions: ["Pattern A", "Pattern B"],
    sizeOptions: ["One Size"],
  },
  {
    id: "fashion-002",
    name: "Signature Abstract Dress",
    vendor: "Joan of Art",
    description: "Flowing art-inspired dress with vibrant design.",
    price: 340,
    productCode: "fashion-002",
    gallery: [{ src: "/products/shirt2.jpg", alt: "Abstract dress" }],
    colorOptions: ["Multicolor"],
    sizeOptions: ["S", "M", "L"],
  },
  {
    id: "fashion-003",
    name: "Painter’s Touch Scarf",
    vendor: "Joan of Art",
    description: "Lightweight scarf featuring brushstroke-inspired patterns.",
    price: 95,
    productCode: "fashion-003",
    gallery: [{ src: "/products/shirt3.jpg", alt: "Painter’s Touch Scarf" }],
    colorOptions: ["Blue tones", "Red tones"],
    sizeOptions: ["One Size"],
  },

  // 👜 Accessories
  {
    id: "accessory-001",
    name: "Art-Inspired Tote",
    vendor: "Joan of Art",
    description: "Canvas tote bag with exclusive Joan of Art print.",
    price: 45,
    productCode: "accessory-001",
    gallery: [{ src: "/products/woman1.jpeg", alt: "Art Tote" }],
    colorOptions: ["Natural Canvas"],
    sizeOptions: ["One Size"],
  },
  {
    id: "accessory-002",
    name: "Geometric Earrings",
    vendor: "Joan of Art",
    description: "Handmade earrings with abstract geometric design.",
    price: 65,
    productCode: "accessory-002",
    gallery: [{ src: "/products/woman2.jpeg", alt: "Geometric Earrings" }],
    colorOptions: ["Gold", "Silver"],
    sizeOptions: ["One Size"],
  },
  {
    id: "accessory-003",
    name: "Statement Necklace",
    vendor: "Joan of Art",
    description: "Bold necklace blending art and fashion into jewelry.",
    price: 120,
    productCode: "accessory-003",
    gallery: [{ src: "/products/woman3.jpeg", alt: "Statement Necklace" }],
    colorOptions: ["Multicolor"],
    sizeOptions: ["One Size"],
  },
  {
    id: "accessory-004",
    name: "Art Lover’s Bracelet",
    vendor: "Joan of Art",
    description: "Unique bracelet inspired by expressive brush strokes.",
    price: 75,
    productCode: "accessory-004",
    gallery: [{ src: "/products/woman4.jpeg", alt: "Bracelet" }],
    colorOptions: ["Black/Gold", "Silver"],
    sizeOptions: ["One Size"],
  },
]
